# Generated by Django 4.0.6 on 2022-07-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='cards_stored',
            field=models.IntegerField(default=0, null=True, verbose_name='Cartes Stockées'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='eggs_hatched',
            field=models.IntegerField(default=0, null=True, verbose_name='Oeuf Stockés'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='food_stored',
            field=models.IntegerField(default=0, null=True, verbose_name='Nourritures Stockées'),
        ),
    ]
