# Generated by Django 4.0.6 on 2022-07-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_bird_cards_stored_alter_bird_eggs_hatched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdcard',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
