# Generated by Django 4.0.6 on 2022-07-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_birdcard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdcard',
            name='bird_power',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stats.birdpower'),
        ),
    ]
