# Generated by Django 4.0.6 on 2022-07-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_birdcard_bird_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdpower',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
