# Generated by Django 4.0.6 on 2022-07-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_birdpower_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdpower',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
