# Generated by Django 4.0.6 on 2022-07-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_alter_birdpower_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='eggs_hatched',
        ),
    ]
