# Generated by Django 4.0.6 on 2022-07-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_remove_bird_eggs_hatched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdpower',
            name='type',
            field=models.CharField(choices=[('HUNT', 'Chasse'), ('FOOD', 'Nourriture'), ('REPRODUCTION', 'Glissez des cartes'), ('EGG', 'Oeuf'), ('CARD_DRAW', 'Pioche'), ('CARD_BONUS', 'Piocher des carte bonus'), ('HATCH_BIRD', 'Poser un autre oiseau'), ('MOVING', 'Déplacement'), ('OTHER', 'Autre')], default=None, max_length=13),
        ),
    ]
