# Generated by Django 4.0.6 on 2022-07-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_alter_birdpower_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdcard',
            name='english_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='birdcard',
            name='extension',
            field=models.CharField(choices=[('CORE', 'Jeu de Base'), ('EUROPA', 'Europe')], default='CORE', max_length=13),
        ),
        migrations.AddField(
            model_name='birdcard',
            name='latin_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='birdcard',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
