# Generated by Django 4.0.6 on 2022-07-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_birdcard_english_name_birdcard_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdcard',
            name='nest_type',
            field=models.CharField(choices=[('BONUS', 'Bonus'), ('BOWL', 'Nid'), ('CAVITY', 'Tronc'), ('GROUND', 'A même le sol'), ('PLATFORM', 'Plateforme')], default=None, max_length=13, null=True),
        ),
    ]
