# Generated by Django 4.0.6 on 2022-07-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_alter_birdcard_nest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdcard',
            name='nest_type',
            field=models.CharField(choices=[('BONUS', 'Bonus'), ('BOWL', 'Nid'), ('CAVITY', 'Tronc'), ('GROUND', 'A même le sol'), ('PLATFORM', 'Plateforme'), ('NOTHING', 'Pas de nid')], default=None, max_length=13, null=True),
        ),
    ]
