# Generated by Django 4.0.6 on 2022-07-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_alter_birdpower_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergame',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Total points'),
        ),
    ]
