# Generated by Django 4.0.6 on 2022-07-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergame',
            name='engine_size',
            field=models.IntegerField(default=0, verbose_name='Taille du moteur'),
        ),
    ]
