# Generated by Django 4.0.6 on 2022-07-30 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_playergame_forest_1_playergame_forest_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='player_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birds', to='stats.playergame'),
        ),
    ]
